### ISSUE TITLE
Standalone pages

### ISSUE THREAD

**Issue by edouard-lopez** [cloudfour/drizzle#100]
Is it possible to create pages that live outside the main navigation and use their own templates?

For instance, we want to create full standalone page to demonstrate some layout (e.g. mobile, hero, etc.)

**Comment by tylersticka** [comment]
It is!

Any page in the `pages/` directory will be output, and you can specify a layout template in Frontmatter.

For example, in our cloudfour.com pattern library we have a `pages/sandbox/` directory for page prototypes: https://github.com/cloudfour/cloudfour.com-patterns/tree/master/src/pages/sandbox

These reference layout templates found here in the Frontmatter: https://github.com/cloudfour/cloudfour.com-patterns/tree/master/src/templates/toolkit

**Comment by edouard-lopez** [comment]
Thanks the `layout` property do indeed fit my need.
