### ISSUE TITLE
Fresh build breaks due to outdated dependencies

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/drizzle#101]
Dependencies (both organizational and public) are way out of date. Default build fails as a result.

(Issue originally reported by @nicolemors)

**Comment by tylersticka** [comment]
@calebeby First priority should be diagnosis: Is this a simple dependency issue, does this require a big overhaul of the build process, etc.?

Possibly (probably?) related issue: cloudfour/core-gulp-tasks#63

**Comment by calebeby** [comment]
@tylersticka the build seems to be working. Does it work for you?

**Comment by gerardo-rodriguez** [comment]
Hmm...I also just tried this and it builds fine for me as well. 🤔 

Steps I followed:

0. Jump into `master` branch and pulled the latest

0. Ran `npm start`

Is that what wasn't working for you @tylersticka?

**Comment by tylersticka** [comment]
- [x] Clone fresh copy
- [x] Run `npm start`… works! 👍 
- [x] Kill `node_modules`
- [x] `rm .nvmrc`
- [x] `nvm use node` (switches to `v10.3.0`)
- [x] Run `npm start` again… also works! 👍 

Did you change anything? 🤔 

@nicolemors Can you check to see if the problem is resolved for you, too?

**Comment by calebeby** [comment]
🤷‍♂️ It seems to work even if I check out 5fdd23051392a9061c1a374915599f7f5493460c, which was before I made any changes.

@tylersticka @gerardo-rodriguez can we close this then?

**Comment by tylersticka** [comment]
@calebeby I think so.

@nicolemors If you encounter this again, please re-open and let us know what version of Node you're using.
