### ISSUE TITLE
The nav is broken

### ISSUE THREAD

**Issue by nefairious** [cloudfour/drizzle#102]
Direct from the template clicking the nav arrow doesn't trigger the menu. Never has. Please fix this soon. My ideal nav trigger is an off-canvas push from the left side but i'd settle with it just working.

**Comment by tylersticka** [comment]
Sorry to hear the nav hasn't been playing nice. ☹️ 

Unfortunately, I haven't been able to reproduce the issue. I just downloaded and ran `npm start` on a fresh copy of Drizzle, and it seems to be working as I'd expect it to:

![drizzle-nav](https://user-images.githubusercontent.com/69633/35992591-8717a0e2-0cbf-11e8-815d-0f213b443bb3.gif)

Some info that might help:

- What browser are you encountering the issue in?
- Are there any JavaScript errors in the console?
- Do you encounter the same issue on a live Drizzle pattern library, [for example ours](http://cloudfour-patterns.netlify.com/)?

> My ideal nav trigger is an off-canvas push from the left side but i'd settle with it just working.

While this isn't the default behavior, you can fully customize Drizzle's UI. CSS and JavaScript are defined in `src/assets/drizzle` and the templates are in `src/templates/drizzle`.

**Comment by nefairious** [comment]
Thanks for the quick response.
It took 3 times but i finally got a download that worked.
I'm attributing it to pulling all the files out of the main Drizzle folder
and dropping it directly into my project folder.
Yes! I don't have to change to another styleguide generator!
