### ISSUE TITLE
Page titles should have defaults

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/drizzle#11]
If `{{title}}` is undefined, we should use the current collection title, or fall back to the project title. It might also be nice to have the project name appended to the title anyway.
## Examples

"Drizzle" represents the project name...

``` html
<!-- If {{title}} is defined: -->
<title>Overview - Drizzle</title>

<!-- Else if collection title is defined: -->
<title>Button - Drizzle</title>

<!-- Else: -->
<title>Drizzle</title>
```

**Comment by gerardo-rodriguez** [comment]
> "Drizzle" represents the project name...

I'm assuming the project name is dynamic and accessible as part of the data?

**Comment by tylersticka** [comment]
> I'm assuming the project name is dynamic and accessible as part of the data?

I'm honestly not sure! If it isn't, then it probably should be. But that may be a separate issue. Probably not the end of the world if this is baked into the template.
