### ISSUE TITLE
Update to latest helpers

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/drizzle#27]
Latest version is `0.2.0`.

See cloudfour/core-hbs-helpers#21

**Comment by gerardo-rodriguez** [comment]
Is this a matter of updating the `package.json`?

From this:

```
"core-hbs-helpers": "github:cloudfour/core-hbs-helpers#v0.1.1"
```

To this?

```
"core-hbs-helpers": "github:cloudfour/core-hbs-helpers#v0.2.0"
```

**Comment by tylersticka** [comment]
@mrgerardorodriguez I guess? ¯\_(ツ)_/¯

I'd have to consult Google or the `npm` docs. Or bug @erikjung. My standard information repositories these days.

**Comment by erikjung** [comment]
@mrgerardorodriguez Yes, just the `package.json`.
