### ISSUE TITLE
Page item and label header markup has some quirks

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/drizzle#28]
- There's too much margin above the titles at large sizes (should probably be margin below thumbs instead).
- We should override padding on labels in case a project doesn't (they are a `<ul>` currently).
- We should allow pattern titles to wrap (not sure why we aren't).

**Comment by megnotarte** [comment]
Small

**Comment by gerardo-rodriguez** [comment]
Hey @tylersticka, could I get some clarification from you on these tasks? Maybe some screenshots?

> There's too much margin above the titles at large sizes (should probably be margin below thumbs instead).

Not sure what this is describing. :)

> We should override padding on labels in case a project doesn't (they are a `<ul>` currently).

This isn't clear to me either. :P

> We should allow pattern titles to wrap (not sure why we aren't).

Is this referring to the `<pre>` code?

Thanks!

**Comment by tylersticka** [comment]
> There's too much margin above the titles at large sizes (should probably be margin below thumbs instead).

Currently the page titles have margin above them. This is fine at small sizes:

![screen shot 2016-05-13 at 3 31 28 pm](https://cloud.githubusercontent.com/assets/69633/15263559/0a16111c-1920-11e6-8d4f-91f0764e9e6d.png)

But at larger sizes when the layout shifts, the upper margin looks kinda funky. This isn't super noticeable until you have a longer description, which we do in other projects:

![screen shot 2016-05-13 at 3 31 49 pm](https://cloud.githubusercontent.com/assets/69633/15263566/1a90bce0-1920-11e6-83f4-08f1944cbe31.png)

---

> We should override padding on labels in case a project doesn't (they are a `<ul>` currently).

The labels are inside of a `<ul>` element, but we aren't overriding the list display of that element in our Drizzle CSS. But if we disable or change `toolkit.css`, they get excess padding on the left:

![screen shot 2016-05-13 at 3 36 14 pm](https://cloud.githubusercontent.com/assets/69633/15263611/7f77694c-1920-11e6-9669-4db90a1f110f.png)

This is because our `toolkit.css` removes `padding-left` from all `<ul>` elements. But that's fairly uncommon in our projects, so ideally our `<ul>` would have its left padding removed (perhaps with a utility class) to avoid this issue.

---

> > We should allow pattern titles to wrap (not sure why we aren't).
> 
> Is this referring to the `<pre>` code?

Nope, the pattern headings. They have a `white-space: nowrap` utility on them, which means longer titles won't break at narrow widths:

![screen shot 2016-05-13 at 3 39 45 pm](https://cloud.githubusercontent.com/assets/69633/15263669/f1e5c456-1920-11e6-92f6-d6e336d14d68.png)

---

@mrgerardorodriguez Responses above, let me know if you have more questions.

**Comment by gerardo-rodriguez** [comment]
Cool, thanks @tylersticka! 😀
