### ISSUE TITLE
Boilerplate listable FPO data

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/drizzle#35]
The typographic specimens are awesome. But I also need this sorta stuff on most (if not all) projects:
- List of user info ([example](http://www.radfaces.com/))
- List of article-like content (title, author, date, excerpt, body)

It'd be pretty great to have some of that included and ready to go, even/especially if it just gets edited to suit project needs. It might also help demonstrate that the `data/` folder can incorporate as many files as one might like.

**Comment by megnotarte** [comment]
Low priority. Small.
