### ISSUE TITLE
HTML beautifier needs more adjustment

### ISSUE THREAD

**Issue by erikjung** [cloudfour/drizzle#39]
Things noticed recently:
- The attribute wrapping might not be worth it to enable
- Extra blank lines are retained
- Mysterious extra whitespace following `</a>` within a lines of text

![screen shot 2016-04-29 at 12 52 55 pm](https://cloud.githubusercontent.com/assets/61204/14927873/5b4a263a-0e09-11e6-8d00-57e1deb167c5.png)

**Comment by megnotarte** [comment]
Small

**Comment by erikjung** [comment]
Closed via #48 

![screen shot 2016-05-09 at 10 37 26 am](https://cloud.githubusercontent.com/assets/61204/15122044/18765952-15d2-11e6-93ca-e12868fa2765.png)
