### ISSUE TITLE
Make assets task registered and configured by default

### ISSUE THREAD

**Issue by erikjung** [cloudfour/drizzle#40]
Currently, the assets task from https://github.com/cloudfour/core-hbs-helpers is present as a dependency, but is not registered or configured in `gulpfile.js` or `config.js` respectively. 

Since it's common to need images and other static assets copied into `dist`, this task should probably be enabled and ready to go.
### Questions
- Which folder location makes the most sense for sourcing? We've used `src/assets/toolkit/` before, but is that what we want as a default?

**Comment by megnotarte** [comment]
Small

**Comment by megnotarte** [comment]
@tylersticka doesn't have a strong opinion but is used to it under `src`. No one else seems to have a preference. @erikjung said he'll put it next to where the stylesheets for the toolkit live.
