### ISSUE TITLE
Support order overrides via frontmatter for pages

### ISSUE THREAD

**Issue by erikjung** [cloudfour/drizzle#42]
https://github.com/cloudfour/drizzle-builder/issues/85

**Comment by megnotarte** [comment]
Med- Large

**Comment by erikjung** [comment]
With the addition of the `pages` helper with a `sortby` hash option, I believe this has been satisfied for _pages_. Not for collections quite yet.

Any `order` added to the front-matter of a page can now be sorted against while using the related helper.

**Comment by erikjung** [comment]
Going to close this for now, via #61
