### ISSUE TITLE
Base URL template variable does nothing

### ISSUE THREAD

**Issue by erikjung** [cloudfour/drizzle#43]
Original issue: https://github.com/cloudfour/drizzle-builder/issues/63
### TODO
- [x] Change builder config so that the `dest` paths for pages, patterns, etc. all assume a common root folder (e.g. `./dist`)

**Comment by megnotarte** [comment]
Feels like a Medium, but warrants more investigation.

**Comment by erikjung** [comment]
Closed via #62
