### ISSUE TITLE
 Project name should be used in relevant templates

### ISSUE THREAD

**Issue by megnotarte** [cloudfour/drizzle#44]
https://github.com/cloudfour/generator-drizzle/issues/9

Small

**Comment by erikjung** [comment]
More info on the plan of attack for this...

The generator is going to be updated to output a default Drizzle data file for template consumption. 

For example, if "My Project" is supplied as a project title during the generator prompting, then a file like this will be created:

``` yaml
# project.yaml
title: My Project
```

and the resulting Drizzle templates will be able to use it as regular data:

``` hbs
<title>{{data "project.title"}}</title>
```

This data file approach will ultimately be more flexible and easier to maintain, compared to writing the user input values to hard-coded HTML.

/CC @mrgerardorodriguez @tylersticka
