### ISSUE TITLE
Longer project title gets cut off

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/drizzle#58]
![screen shot 2016-05-16 at 3 55 49 pm](https://cloud.githubusercontent.com/assets/459757/15306357/ca92f5bc-1b7e-11e6-8709-6a5dda5ef485.png)

**Comment by saralohr** [comment]
Ah, I wasn't envisioning this as a generated field, more as a self contained logo that could be manually replaced. If it is dynamic we can use a different approach for the title rather than including it in the SVG.

**Comment by gerardo-rodriguez** [comment]
I see. Yep, https://github.com/cloudfour/drizzle/issues/44 introduces a [generated title field](https://github.com/cloudfour/drizzle/blob/master/src/templates/drizzle/logo.hbs#L5) that will live in the [project.yaml](https://github.com/cloudfour/drizzle/blob/master/src/data/project.yaml). :)

**Comment by tylersticka** [comment]
As mentioned in my conversation earlier with @erikjung, I don't think this area _should_ be dynamic. Originally it was text-based, but I think that's a bad idea now that there's a logo there. And it would be weird to have the Drizzle icon next to some other type.

I _do_ think the project name should populate the `<title>` element in the head, though.

**Comment by gerardo-rodriguez** [comment]
@tylersticka Ah, right! I forgot about that. Sorry! I'll create a new PR that removes this for the logo. 😉

**Comment by gerardo-rodriguez** [comment]
No longer an issue, closing! 😁
