### ISSUE TITLE
Demo site

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/drizzle#70]
We need a publicly-accessible demo! 😃 

This could be a Netlify site, or we could use something like [`gulp-gh-pages`](https://www.npmjs.com/package/gulp-gh-pages) to use GitHub pages.

**Comment by erikjung** [comment]
So, I see this as:

**Option A: Netlify**
- [ ] Create `drizzle-demo` repo
- [ ] Hook up Netlify integration
- [ ] Commit the contents (`dist`) of a build to the master branch of that repo

**Option B: GitHub Pages**
- [x] Create a `gh-pages` branch on this repo
- [x] Add a task (or some automation) to get the contents of a build into that branch

Option B seems more painless to me. One less repo to keep up to date.

**Comment by tylersticka** [comment]
@erikjung I agree!

**Comment by erikjung** [comment]
Closed via #72
