### ISSUE TITLE
Discuss dev dependency gulp-gh-pages

### ISSUE THREAD

**Issue by derekshirk** [cloudfour/drizzle#97]
`gulp-gh-pages` is currently listed as a dev dependency in `package.json`. Is this still necessary?

https://github.com/cloudfour/drizzle/blob/5fdd23051392a9061c1a374915599f7f5493460c/package.json#L41

**Comment by tylersticka** [comment]
Maybe, maybe not. See #72 for history.

**Comment by calebeby** [comment]
Do we still need the `demo` functionality? (Is that a feature that is actually used?)

**Comment by calebeby** [comment]
Should I switch it from `gulp-gh-pages` to `gh-pages`? Should I try to switch it to deploy it to netlify?

**Comment by tylersticka** [comment]
Hmm... so I think what's happened is that when we launched Drizzle, the GitHub demo had to occupy a special `gh-pages` branch:

https://github.com/cloudfour/drizzle/blob/6d53e7d4d20e671c9c55da2362573a246bc9a2cd/gulpfile.js#L48-L58

While this is only necessary for the demo, I think it means we can't remove it unless we [redo how the demo is sourced](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/)?

/CC @derekshirk @gerardo-rodriguez

**Comment by gerardo-rodriguez** [comment]
> Should I try to switch it to deploy it to netlify?

@tylersticka @derekshirk I honestly can't remember if we'd shifted over to using Netlify around the time of #72. I wouldn't mind shifting it over to Netlify. Do either of you see a reason why we shouldn't do this?

/cc @calebeby

**Comment by tylersticka** [comment]
@gerardo-rodriguez We use Netlify on our projects, but the Drizzle demo is in GitHub pages: http://cloudfour.github.io/drizzle/

At the time, I think our logic was that there wasn't a need to add a separate hosting dependency for a simple demo. I also think it was when Netlify was young and maybe didn't have as nice of a free plan? I'm open to switching this up if we decide to host the demo elsewhere, as long as we make sure any links (not just here, but in our blog posts and stuff) are updated or redirected.

**Comment by calebeby** [comment]
So if we want to keep the `demo` functionality, and are fine with sticking to GitHub pages for it, I don't think there is a reason to remove the `gulp-gh-pages` dependency. Can I close this?

**Comment by gerardo-rodriguez** [comment]
> as long as we make sure any links (not just here, but in our blog posts and stuff) are updated or redirected.

Good point @tylersticka. If I'm honest, this is something I wouldn't want to do unless it absolutely _had_ to be done. 😬 

> So if we want to keep the demo functionality, and are fine with sticking to GitHub pages for it, I don't think there is a reason to remove the gulp-gh-pages dependency. Can I close this?

@calebeby This sounds correct to me.

**Comment by calebeby** [comment]
OK, closing
